module_name: APCu Cache Manager
compatible_versions: 1.0.0+
author: thirty bees
category: administraion
sub-category: cache management
tags:
  - cache
  - apc
  - apcu
  - cache manger
short_description: The official thirty bees APCu module allows you to monitor and clear your APCu cache from your shop's back office.
description: description.md
images:
  - image-1.png
  - image-2.png
license: MIT

